/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quizartvantgarde;

import javax.swing.JOptionPane;

/**
 *
 * @author louis
 */
public class TelaPerguntas extends javax.swing.JFrame {
    static int idLogin;
    static int idVanguarda;
    static Musica musica;
    static DAO dao = new DAO();
    public int codQuestao = 0;
    static int qtdeAcertos = 0;
    static int qtdeErros = 0;
    
    public TelaPerguntas(int idLogin, int idVanguarda, Musica musica) {
        super("Quiz ArtVantGarde");
        initComponents();
        this.setLocationRelativeTo(null);
        this.idVanguarda = idVanguarda;
        this.idLogin = idLogin;
        this.musica = musica;
        perguntaTextArea.setLineWrap(true);
        perguntaTextArea.setWrapStyleWord(true);
        respostaCorretaTextArea.setLineWrap(true);
        respostaCorretaTextArea.setWrapStyleWord(true);
        respostaIncorreta1TextArea.setLineWrap(true);
        respostaIncorreta1TextArea.setWrapStyleWord(true);
        respostaIncorreta2TextArea.setLineWrap(true);
        respostaIncorreta2TextArea.setWrapStyleWord(true);
        respostaIncorreta3TextArea.setLineWrap(true);
        respostaIncorreta3TextArea.setWrapStyleWord(true);
        try{
            questoesTable.setModel(new QuestaoTableModel(idVanguarda));
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Problemas Técnicos!!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogoPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        adicionarPerguntaButton = new javax.swing.JButton();
        alterarPerguntaButton = new javax.swing.JButton();
        removerPerguntaButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        menuPrincipalButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        perguntaTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        urlImagemTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        respostaCorretaTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        respostaIncorreta1TextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        respostaIncorreta2TextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        respostaIncorreta3TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        questoesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jogoPanel.setBackground(new java.awt.Color(222, 209, 193));
        jogoPanel.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jogoPanel.setPreferredSize(new java.awt.Dimension(1596, 848));

        jLabel6.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/h2iNDe1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        jPanel2.setBackground(new java.awt.Color(234, 229, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));

        adicionarPerguntaButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        adicionarPerguntaButton.setText("Adicionar Pergunta");
        adicionarPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarPerguntaButtonActionPerformed(evt);
            }
        });

        alterarPerguntaButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        alterarPerguntaButton.setText("Alterar Pergunta");
        alterarPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarPerguntaButtonActionPerformed(evt);
            }
        });

        removerPerguntaButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        removerPerguntaButton.setText("Remover Pergunta");
        removerPerguntaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPerguntaButtonActionPerformed(evt);
            }
        });

        voltarButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        menuPrincipalButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        menuPrincipalButton.setText("Menu Principal");
        menuPrincipalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removerPerguntaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alterarPerguntaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adicionarPerguntaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voltarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPrincipalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(adicionarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alterarPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removerPerguntaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuPrincipalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(234, 229, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel2.setText("Pergunta:");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel3.setText("URL da Imagem:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel4.setText("Resposta Incorreta 1:");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel5.setText("Resposta Correta:");

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel8.setText("Resposta Incorreta 2:");

        perguntaTextArea.setColumns(20);
        perguntaTextArea.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        perguntaTextArea.setRows(5);
        jScrollPane1.setViewportView(perguntaTextArea);

        urlImagemTextArea.setColumns(20);
        urlImagemTextArea.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        urlImagemTextArea.setRows(5);
        jScrollPane3.setViewportView(urlImagemTextArea);

        respostaCorretaTextArea.setColumns(20);
        respostaCorretaTextArea.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        respostaCorretaTextArea.setRows(5);
        jScrollPane4.setViewportView(respostaCorretaTextArea);

        respostaIncorreta1TextArea.setColumns(20);
        respostaIncorreta1TextArea.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        respostaIncorreta1TextArea.setRows(5);
        jScrollPane5.setViewportView(respostaIncorreta1TextArea);

        respostaIncorreta2TextArea.setColumns(20);
        respostaIncorreta2TextArea.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        respostaIncorreta2TextArea.setRows(5);
        jScrollPane6.setViewportView(respostaIncorreta2TextArea);

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel9.setText("Resposta Incorreta 3:");

        respostaIncorreta3TextArea.setColumns(20);
        respostaIncorreta3TextArea.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        respostaIncorreta3TextArea.setRows(5);
        jScrollPane7.setViewportView(respostaIncorreta3TextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Perguntas");

        jScrollPane2.setToolTipText("");

        questoesTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        questoesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código da Questão", "Pergunta", "URL da Imagem", "Resposta Correta", "Resposta Incorreta 1", "Resposta Incorreta 2", "Resposta Incorreta 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        questoesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                questoesTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(questoesTable);

        javax.swing.GroupLayout jogoPanelLayout = new javax.swing.GroupLayout(jogoPanel);
        jogoPanel.setLayout(jogoPanelLayout);
        jogoPanelLayout.setHorizontalGroup(
            jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogoPanelLayout.createSequentialGroup()
                .addGroup(jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jogoPanelLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jogoPanelLayout.createSequentialGroup()
                        .addGap(723, 723, 723)
                        .addComponent(jLabel1)))
                .addContainerGap(344, Short.MAX_VALUE))
            .addGroup(jogoPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jogoPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        jogoPanelLayout.setVerticalGroup(
            jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1596, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPrincipalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalButtonActionPerformed
        try{
            if(dao.existeProfessor(idLogin)){
                TelaMenuPrincipalProfessor frame = new TelaMenuPrincipalProfessor(idLogin, musica);
                this.dispose();
                frame.setVisible(true);
            }else{
                TelaMenuPrincipalAdmin frame = new TelaMenuPrincipalAdmin(idLogin, musica);
                this.dispose();
                frame.setVisible(true);
            }
        }catch (Exception e){
           JOptionPane.showMessageDialog(null, "Problemas Técnicos!!"); 
        }
    }//GEN-LAST:event_menuPrincipalButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        TelaVanguardasPerguntas frame = new TelaVanguardasPerguntas(idLogin, musica);
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void removerPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPerguntaButtonActionPerformed
        Object[] options = {"Sim", "Cancelar"};
        int escolha = JOptionPane.showOptionDialog(null, "Você tem certeza de que deseja deletar este cadastro?",
        "Quiz ArtVantGarde",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,           //do not use a custom Icon
        options,        //the titles of buttons
        options[0]);    //default button title
        if(escolha == JOptionPane.YES_OPTION){
            try{
                dao.apagarQuestao(codQuestao);
                questoesTable.setModel(new QuestaoTableModel(idVanguarda));
                perguntaTextArea.setText("");
                respostaCorretaTextArea.setText("");
                respostaIncorreta1TextArea.setText("");
                respostaIncorreta2TextArea.setText("");
                respostaIncorreta3TextArea.setText("");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "É preciso selecionar uma pergunta!", "Quiz ArtVantGarde", 0);
            }
        }
    }//GEN-LAST:event_removerPerguntaButtonActionPerformed

    private void alterarPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarPerguntaButtonActionPerformed
        String pergunta = perguntaTextArea.getText();
        String respostaCorreta = respostaCorretaTextArea.getText();
        String respostaIncorreta1 = respostaIncorreta1TextArea.getText();
        String respostaIncorreta2 = respostaIncorreta2TextArea.getText();
        String respostaIncorreta3 = respostaIncorreta3TextArea.getText();
        
        if(pergunta.isBlank() || respostaCorreta.isBlank() || respostaIncorreta1.isBlank() || respostaIncorreta2.isBlank() || respostaIncorreta3.isBlank()){
            JOptionPane.showMessageDialog(null, "É preciso preencher todos os campos!", "Quiz ArtVantGarde", 0);
        }else{
            Questao questao = new Questao(codQuestao, pergunta, urlImagemTextArea.getText(), 
                    respostaCorreta, respostaIncorreta1, respostaIncorreta2, respostaIncorreta3, idVanguarda);
            try{
                if(dao.existeQuestao(questao)){
                    try {
                        dao.alterarQuestao(questao);
                        questoesTable.setModel(new QuestaoTableModel(idVanguarda));
                        perguntaTextArea.setText("");
                        urlImagemTextArea.setText("");
                        respostaCorretaTextArea.setText("");
                        respostaIncorreta1TextArea.setText("");
                        respostaIncorreta2TextArea.setText("");
                        respostaIncorreta3TextArea.setText("");
                    }catch (Exception e){
                        JOptionPane.showMessageDialog(null, "É preciso selecionar uma questao!");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "A questão que você esta tentando alterar não existe ou não pôde ser encontrada!");
                }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
            }
        }
    }//GEN-LAST:event_alterarPerguntaButtonActionPerformed

    private void adicionarPerguntaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarPerguntaButtonActionPerformed
        String pergunta = perguntaTextArea.getText();
        String respostaCorreta = respostaCorretaTextArea.getText();
        String respostaIncorreta1 = respostaIncorreta1TextArea.getText();
        String respostaIncorreta2 = respostaIncorreta2TextArea.getText();
        String respostaIncorreta3 = respostaIncorreta3TextArea.getText();
        
        if(pergunta.isBlank() || respostaCorreta.isBlank() || respostaIncorreta1.isBlank() || respostaIncorreta2.isBlank() || respostaIncorreta3.isBlank()){
            JOptionPane.showMessageDialog(null, "É preciso preencher todos os campos!", "Quiz ArtVantGarde", 0);
        }else{
            Questao questao = new Questao(codQuestao, pergunta, urlImagemTextArea.getText(), 
                    respostaCorreta, respostaIncorreta1, respostaIncorreta2, respostaIncorreta3, idVanguarda);
            try{
                if(dao.existeQuestao(questao)){
                    JOptionPane.showMessageDialog(null, "A questão inserida já existe");
                }else{
                        dao.cadastrarQuestao(questao);
                        questoesTable.setModel(new QuestaoTableModel(idVanguarda));
                        perguntaTextArea.setText("");
                        urlImagemTextArea.setText("");
                        respostaCorretaTextArea.setText("");
                        respostaIncorreta1TextArea.setText("");
                        respostaIncorreta2TextArea.setText("");
                        respostaIncorreta3TextArea.setText("");
                }
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
            }
        }
    }//GEN-LAST:event_adicionarPerguntaButtonActionPerformed

    private void questoesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_questoesTableMouseClicked
        int selectedRows = questoesTable.getSelectedRow();
        perguntaTextArea.setText((String) questoesTable.getValueAt(selectedRows, 1));
        urlImagemTextArea.setText((String) questoesTable.getValueAt(selectedRows, 2));
        respostaCorretaTextArea.setText((String) questoesTable.getValueAt(selectedRows, 3));
        respostaIncorreta1TextArea.setText((String) questoesTable.getValueAt(selectedRows, 4));
        respostaIncorreta2TextArea.setText((String) questoesTable.getValueAt(selectedRows, 5));
        respostaIncorreta3TextArea.setText((String) questoesTable.getValueAt(selectedRows, 6));
        codQuestao = (Integer)questoesTable.getValueAt(selectedRows, 0);
    }//GEN-LAST:event_questoesTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerguntas(idLogin, idVanguarda, musica).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarPerguntaButton;
    private javax.swing.JButton alterarPerguntaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel jogoPanel;
    private javax.swing.JButton menuPrincipalButton;
    private javax.swing.JTextArea perguntaTextArea;
    private javax.swing.JTable questoesTable;
    private javax.swing.JButton removerPerguntaButton;
    private javax.swing.JTextArea respostaCorretaTextArea;
    private javax.swing.JTextArea respostaIncorreta1TextArea;
    private javax.swing.JTextArea respostaIncorreta2TextArea;
    private javax.swing.JTextArea respostaIncorreta3TextArea;
    private javax.swing.JTextArea urlImagemTextArea;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
