import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author louis
 */
public class TelaAlterarCadastro extends javax.swing.JFrame {
    static int idLogin;
    static Musica musica;
    static DAO dao = new DAO();
    public ArrayList<String> cadastroProfessor;
    public ArrayList<String> cadastroAluno;
    /**
     * Creates new form TelaAlterarCadastro
     */
    public TelaAlterarCadastro(int idLogin, Musica musica) {
        super("Quiz ArtVantGarde");
        initComponents();
        this.setLocationRelativeTo(null);
        this.musica = musica;
        this.idLogin = idLogin;
        
        try{
            if(dao.existeProfessor(idLogin)){
                cadastroAlunoPanel.setVisible(false);
                alunoButtonPanel.setVisible(false);
                esconderSenhaProfessorLabel.setVisible(false);
                cadastroProfessor = dao.pegarCadastrosProfessores(this.idLogin);
                emailProfessorTextField.setText(cadastroProfessor.get(0));
                senhaProfessorPasswordField.setText(cadastroProfessor.get(1));
                nomeProfessorTextField.setText(cadastroProfessor.get(2));
                materiaLecionadaTextField.setText(cadastroProfessor.get(3));
            }else if(dao.existeAluno(idLogin)){
                cadastroProfessorPanel.setVisible(false);
                professorButtonPanel.setVisible(false);
                esconderSenhaAlunoLabel.setVisible(false);
                cadastroAluno = dao.pegarCadastrosAlunos(this.idLogin);
                emailAlunoTextField.setText(cadastroAluno.get(0));
                senhaAlunoPasswordField.setText(cadastroAluno.get(1));
                nomeAlunoTextField.setText(cadastroAluno.get(2));
                serieTextField.setText(cadastroAluno.get(3));
                codMatriculaTextField.setText(cadastroAluno.get(4));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        criarCadastroLabel = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        cadastroAlunoPanel = new javax.swing.JPanel();
        emailAlunoTextField = new javax.swing.JTextField();
        insiraEmailLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        senhaAlunoPasswordField = new javax.swing.JPasswordField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        verSenhaAlunoLabel = new javax.swing.JLabel();
        esconderSenhaAlunoLabel = new javax.swing.JLabel();
        nomeAlunoTextField = new javax.swing.JTextField();
        serieTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        codMatriculaTextField = new javax.swing.JTextField();
        cadastroProfessorPanel = new javax.swing.JPanel();
        emailProfessorTextField = new javax.swing.JTextField();
        insiraEmailLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        senhaProfessorPasswordField = new javax.swing.JPasswordField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        verSenhaProfessorLabel = new javax.swing.JLabel();
        esconderSenhaProfessorLabel = new javax.swing.JLabel();
        nomeProfessorTextField = new javax.swing.JTextField();
        materiaLecionadaTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        alunoButtonPanel = new javax.swing.JPanel();
        alterarAlunoButton = new javax.swing.JButton();
        menuPrincipalAlunoButton = new javax.swing.JButton();
        apagarAlunoButton = new javax.swing.JButton();
        voltarAlunoButton = new javax.swing.JButton();
        professorButtonPanel = new javax.swing.JPanel();
        alterarProfessorButton = new javax.swing.JButton();
        menuPrincipalProfessorButton = new javax.swing.JButton();
        apagarProfessorButton = new javax.swing.JButton();
        voltarProfessorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 209, 193));
        jPanel1.setPreferredSize(new java.awt.Dimension(1596, 848));

        logoLabel.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("https://i.imgur.com/mf4A0bx.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        criarCadastroLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        criarCadastroLabel.setText("Configurações - Conta");

        cadastroAlunoPanel.setBackground(new java.awt.Color(234, 229, 222));
        cadastroAlunoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));

        emailAlunoTextField.setBackground(new java.awt.Color(238, 238, 238));
        emailAlunoTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        emailAlunoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAlunoTextFieldActionPerformed(evt);
            }
        });

        insiraEmailLabel.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        insiraEmailLabel.setText("Email:");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel2.setText("Série:");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setText("Senha:");

        senhaAlunoPasswordField.setBackground(new java.awt.Color(238, 238, 238));
        senhaAlunoPasswordField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N

        verSenhaAlunoLabel.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        verSenhaAlunoLabel.setText("Ver Senha");
        verSenhaAlunoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));
        verSenhaAlunoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verSenhaAlunoLabelMouseClicked(evt);
            }
        });

        esconderSenhaAlunoLabel.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        esconderSenhaAlunoLabel.setText("Esconder Senha");
        esconderSenhaAlunoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));
        esconderSenhaAlunoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esconderSenhaAlunoLabelMouseClicked(evt);
            }
        });

        jLayeredPane1.setLayer(verSenhaAlunoLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(esconderSenhaAlunoLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(verSenhaAlunoLabel)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(esconderSenhaAlunoLabel)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verSenhaAlunoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(esconderSenhaAlunoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        nomeAlunoTextField.setBackground(new java.awt.Color(238, 238, 238));
        nomeAlunoTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        nomeAlunoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAlunoTextFieldActionPerformed(evt);
            }
        });

        serieTextField.setBackground(new java.awt.Color(238, 238, 238));
        serieTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        serieTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel3.setText("Nome Completo:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel4.setText("Código de Matrícula:");

        codMatriculaTextField.setBackground(new java.awt.Color(238, 238, 238));
        codMatriculaTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        codMatriculaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codMatriculaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroAlunoPanelLayout = new javax.swing.GroupLayout(cadastroAlunoPanel);
        cadastroAlunoPanel.setLayout(cadastroAlunoPanelLayout);
        cadastroAlunoPanelLayout.setHorizontalGroup(
            cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroAlunoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroAlunoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(nomeAlunoTextField))
                    .addGroup(cadastroAlunoPanelLayout.createSequentialGroup()
                        .addGroup(cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(insiraEmailLabel))
                        .addGap(18, 18, 18)
                        .addGroup(cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailAlunoTextField)
                            .addGroup(cadastroAlunoPanelLayout.createSequentialGroup()
                                .addComponent(senhaAlunoPasswordField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(cadastroAlunoPanelLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(serieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(codMatriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        cadastroAlunoPanelLayout.setVerticalGroup(
            cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroAlunoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailAlunoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insiraEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(senhaAlunoPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeAlunoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroAlunoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(codMatriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cadastroProfessorPanel.setBackground(new java.awt.Color(234, 229, 222));
        cadastroProfessorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));

        emailProfessorTextField.setBackground(new java.awt.Color(238, 238, 238));
        emailProfessorTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        emailProfessorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailProfessorTextFieldActionPerformed(evt);
            }
        });

        insiraEmailLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        insiraEmailLabel1.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel5.setText("Matéria Lecionada:");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel6.setText("Senha:");

        senhaProfessorPasswordField.setBackground(new java.awt.Color(238, 238, 238));
        senhaProfessorPasswordField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N

        verSenhaProfessorLabel.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        verSenhaProfessorLabel.setText("Ver Senha");
        verSenhaProfessorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));
        verSenhaProfessorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verSenhaProfessorLabelMouseClicked(evt);
            }
        });

        esconderSenhaProfessorLabel.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        esconderSenhaProfessorLabel.setText("Esconder Senha");
        esconderSenhaProfessorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));
        esconderSenhaProfessorLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                esconderSenhaProfessorLabelMouseClicked(evt);
            }
        });

        jLayeredPane3.setLayer(verSenhaProfessorLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(esconderSenhaProfessorLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(verSenhaProfessorLabel)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(esconderSenhaProfessorLabel)
                    .addContainerGap()))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verSenhaProfessorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(esconderSenhaProfessorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        nomeProfessorTextField.setBackground(new java.awt.Color(238, 238, 238));
        nomeProfessorTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        nomeProfessorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProfessorTextFieldActionPerformed(evt);
            }
        });

        materiaLecionadaTextField.setBackground(new java.awt.Color(238, 238, 238));
        materiaLecionadaTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        materiaLecionadaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaLecionadaTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel7.setText("Nome Completo:");

        javax.swing.GroupLayout cadastroProfessorPanelLayout = new javax.swing.GroupLayout(cadastroProfessorPanel);
        cadastroProfessorPanel.setLayout(cadastroProfessorPanelLayout);
        cadastroProfessorPanelLayout.setHorizontalGroup(
            cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroProfessorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroProfessorPanelLayout.createSequentialGroup()
                        .addGroup(cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(insiraEmailLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailProfessorTextField)
                            .addGroup(cadastroProfessorPanelLayout.createSequentialGroup()
                                .addComponent(senhaProfessorPasswordField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(cadastroProfessorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroProfessorPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(materiaLecionadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 177, Short.MAX_VALUE))
                            .addComponent(nomeProfessorTextField))))
                .addContainerGap())
        );
        cadastroProfessorPanelLayout.setVerticalGroup(
            cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroProfessorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailProfessorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insiraEmailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(senhaProfessorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeProfessorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroProfessorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiaLecionadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setLayer(cadastroAlunoPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(cadastroProfessorPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroAlunoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cadastroProfessorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroAlunoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(cadastroProfessorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        alunoButtonPanel.setBackground(new java.awt.Color(234, 229, 222));
        alunoButtonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));

        alterarAlunoButton.setBackground(new java.awt.Color(238, 238, 238));
        alterarAlunoButton.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        alterarAlunoButton.setText("Alterar Conta");
        alterarAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarAlunoButtonActionPerformed(evt);
            }
        });

        menuPrincipalAlunoButton.setBackground(new java.awt.Color(238, 238, 238));
        menuPrincipalAlunoButton.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        menuPrincipalAlunoButton.setText("Menu Principal");
        menuPrincipalAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalAlunoButtonActionPerformed(evt);
            }
        });

        apagarAlunoButton.setBackground(new java.awt.Color(238, 238, 238));
        apagarAlunoButton.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        apagarAlunoButton.setText("Apagar Conta");
        apagarAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarAlunoButtonActionPerformed(evt);
            }
        });

        voltarAlunoButton.setBackground(new java.awt.Color(238, 238, 238));
        voltarAlunoButton.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        voltarAlunoButton.setText("Voltar");
        voltarAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAlunoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alunoButtonPanelLayout = new javax.swing.GroupLayout(alunoButtonPanel);
        alunoButtonPanel.setLayout(alunoButtonPanelLayout);
        alunoButtonPanelLayout.setHorizontalGroup(
            alunoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunoButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alterarAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apagarAlunoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(voltarAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuPrincipalAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        alunoButtonPanelLayout.setVerticalGroup(
            alunoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alunoButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alunoButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterarAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuPrincipalAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apagarAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarAlunoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        professorButtonPanel.setBackground(new java.awt.Color(234, 229, 222));
        professorButtonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));

        alterarProfessorButton.setBackground(new java.awt.Color(238, 238, 238));
        alterarProfessorButton.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        alterarProfessorButton.setText("Alterar Conta");
        alterarProfessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarProfessorButtonActionPerformed(evt);
            }
        });

        menuPrincipalProfessorButton.setBackground(new java.awt.Color(238, 238, 238));
        menuPrincipalProfessorButton.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        menuPrincipalProfessorButton.setText("Menu Principal");
        menuPrincipalProfessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalProfessorButtonActionPerformed(evt);
            }
        });

        apagarProfessorButton.setBackground(new java.awt.Color(238, 238, 238));
        apagarProfessorButton.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        apagarProfessorButton.setText("Apagar Conta");
        apagarProfessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarProfessorButtonActionPerformed(evt);
            }
        });

        voltarProfessorButton.setBackground(new java.awt.Color(238, 238, 238));
        voltarProfessorButton.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        voltarProfessorButton.setText("Voltar");
        voltarProfessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarProfessorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout professorButtonPanelLayout = new javax.swing.GroupLayout(professorButtonPanel);
        professorButtonPanel.setLayout(professorButtonPanelLayout);
        professorButtonPanelLayout.setHorizontalGroup(
            professorButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alterarProfessorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(apagarProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(voltarProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuPrincipalProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        professorButtonPanelLayout.setVerticalGroup(
            professorButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(professorButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorButtonPanelLayout.createSequentialGroup()
                        .addGroup(professorButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alterarProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuPrincipalProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apagarProfessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(voltarProfessorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLayeredPane4.setLayer(alunoButtonPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(professorButtonPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alunoButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(professorButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alunoButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane4Layout.createSequentialGroup()
                    .addComponent(professorButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(logoLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(criarCadastroLabel)
                        .addGap(613, 613, 613))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(396, 396, 396))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criarCadastroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void emailAlunoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void verSenhaAlunoLabelMouseClicked(java.awt.event.MouseEvent evt) {                                                
        verSenhaAlunoLabel.setVisible(false);
        esconderSenhaAlunoLabel.setVisible(true);
        senhaAlunoPasswordField.setEchoChar((char)0);
    }                                               

    private void esconderSenhaAlunoLabelMouseClicked(java.awt.event.MouseEvent evt) {                                                     
        verSenhaAlunoLabel.setVisible(true);
        esconderSenhaAlunoLabel.setVisible(false);
        senhaAlunoPasswordField.setEchoChar('*');
    }                                                    

    private void alterarAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        String email = emailAlunoTextField.getText();
        String senha = new String(senhaAlunoPasswordField.getPassword());
        String nomeCompleto = nomeAlunoTextField.getText();
        String serie = serieTextField.getText();
        String codMatricula = codMatriculaTextField.getText();
        if(email.isBlank() || senha.isBlank() || nomeCompleto.isBlank() || serie.isBlank() || codMatricula.isBlank()){
            JOptionPane.showMessageDialog(null, "É preciso preencher todos os campos!", "Quiz ArtVantGarde", 0);
        }else{        
            Login login = new Login(idLogin, email, senha);
            UsuarioAluno aluno = new UsuarioAluno(nomeCompleto, email, codMatricula, idLogin);
            try{
                dao.alterarCadastro(login);
                dao.alterarAluno(aluno);
                JOptionPane.showMessageDialog(null, "Conta alterada com sucesso! Retornando à tela de Login!", "Quiz ArtVantGarde", 1);
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Problemas Técnicos!!", "Quiz ArtVantGarde", 1);
            }
        }
    }                                                  

    private void nomeAlunoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void serieTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void codMatriculaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void menuPrincipalAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        try{
            if(dao.existeProfessor(idLogin)){
                TelaMenuPrincipalProfessor frame = new TelaMenuPrincipalProfessor(idLogin, musica);
                this.dispose();
                frame.setVisible(true);
            }else if(dao.existeAluno(idLogin)){
                TelaMenuPrincipalAluno frame = new TelaMenuPrincipalAluno(idLogin, musica);
                this.dispose();
                frame.setVisible(true);
            }else{
                TelaMenuPrincipalAdmin frame = new TelaMenuPrincipalAdmin(idLogin, musica);
                this.dispose();
                frame.setVisible(true);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
        }
    }                                                        

    private void apagarAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        Object[] options = {"Sim", "Cancelar"};
        int escolha = JOptionPane.showOptionDialog(null, "Você tem certeza de que deseja deletar sua conta?",
        "Quiz ArtVantGarde",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,           //do not use a custom Icon
        options,        //the titles of buttons
        options[0]);    //default button title
        if(escolha == JOptionPane.YES_OPTION){
            try{
                dao.apagarAluno(idLogin);
                dao.apagarLogin(idLogin);
                JOptionPane.showMessageDialog(null, "Conta apagada com sucesso! Retornando à tela de Login!", "Quiz ArtVantGarde", 1);
                TelaFazerLogin frame = new TelaFazerLogin();
                this.dispose();
                frame.setVisible(true);
                musica.pauseMusic();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
            }
        }
    }                                                 

    private void voltarAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        TelaConfiguracoes frame = new TelaConfiguracoes(idLogin, musica);
        this.dispose();
        frame.setVisible(true);
    }                                                 

    private void emailProfessorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void verSenhaProfessorLabelMouseClicked(java.awt.event.MouseEvent evt) {                                                    
        verSenhaProfessorLabel.setVisible(false);
        esconderSenhaProfessorLabel.setVisible(true);
        senhaProfessorPasswordField.setEchoChar((char)0);
    }                                                   

    private void esconderSenhaProfessorLabelMouseClicked(java.awt.event.MouseEvent evt) {                                                         
        verSenhaProfessorLabel.setVisible(true);
        esconderSenhaProfessorLabel.setVisible(false);
        senhaProfessorPasswordField.setEchoChar('*');
    }                                                        

    private void nomeProfessorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void materiaLecionadaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
    }                                                         

    private void alterarProfessorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        String email = emailProfessorTextField.getText();
        String senha = new String(senhaProfessorPasswordField.getPassword());
        String nomeCompleto = nomeProfessorTextField.getText();
        String materiaLecionada = materiaLecionadaTextField.getText();
        if(email.isBlank() || senha.isBlank() || nomeCompleto.isBlank() || materiaLecionada.isBlank()){
            JOptionPane.showMessageDialog(null, "É preciso preencher todos os campos!", "Quiz ArtVantGarde", 0);
        }else{
            try{
                Login login = new Login(idLogin, email, senha);
                UsuarioProfessor prof = new UsuarioProfessor(idLogin, nomeCompleto, materiaLecionada);
                dao.alterarCadastro(login);
                dao.alterarProfessor(prof);
                JOptionPane.showMessageDialog(null, "Conta alterada com sucesso!", "Quiz ArtVantGarde", 1);
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Problemas Técnicos!!", "Quiz ArtVantGarde", 1);
            }
        }
    }                                                      

    private void menuPrincipalProfessorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        try{
            if(dao.existeProfessor(idLogin)){
                TelaMenuPrincipalProfessor frame = new TelaMenuPrincipalProfessor(idLogin, musica);
                this.dispose();
                frame.setVisible(true);
            }else if(dao.existeAluno(idLogin)){
                TelaMenuPrincipalAluno frame = new TelaMenuPrincipalAluno(idLogin, musica);
                this.dispose();
                frame.setVisible(true);
            }else{
                TelaMenuPrincipalAdmin frame = new TelaMenuPrincipalAdmin(idLogin, musica);
                this.dispose();
                frame.setVisible(true);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
        }
    }                                                            

    private void apagarProfessorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        Object[] options = {"Sim", "Cancelar"};
        int escolha = JOptionPane.showOptionDialog(null, "Você tem certeza de que deseja deletar sua conta?",
        "Quiz ArtVantGarde",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,           //do not use a custom Icon
        options,        //the titles of buttons
        options[0]);    //default button title
        if(escolha == JOptionPane.YES_OPTION){
            try{
                dao.apagarProfessor(idLogin);
                dao.apagarLogin(idLogin);
                JOptionPane.showMessageDialog(null, "Conta apagada com sucesso! Retornando à tela de Login!", "Quiz ArtVantGarde", 1);
                TelaFazerLogin frame = new TelaFazerLogin();
                this.dispose();
                frame.setVisible(true);
                musica.pauseMusic();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
            }
        }
    }                                                     

    private void voltarProfessorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        TelaConfiguracoes frame = new TelaConfiguracoes(idLogin, musica);
        this.dispose();
        frame.setVisible(true);
    }                                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarCadastro(idLogin, musica).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton alterarAlunoButton;
    private javax.swing.JButton alterarProfessorButton;
    private javax.swing.JPanel alunoButtonPanel;
    private javax.swing.JButton apagarAlunoButton;
    private javax.swing.JButton apagarProfessorButton;
    private javax.swing.JPanel cadastroAlunoPanel;
    private javax.swing.JPanel cadastroProfessorPanel;
    private javax.swing.JTextField codMatriculaTextField;
    private javax.swing.JLabel criarCadastroLabel;
    private javax.swing.JTextField emailAlunoTextField;
    private javax.swing.JTextField emailProfessorTextField;
    private javax.swing.JLabel esconderSenhaAlunoLabel;
    private javax.swing.JLabel esconderSenhaProfessorLabel;
    private javax.swing.JLabel insiraEmailLabel;
    private javax.swing.JLabel insiraEmailLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField materiaLecionadaTextField;
    private javax.swing.JButton menuPrincipalAlunoButton;
    private javax.swing.JButton menuPrincipalProfessorButton;
    private javax.swing.JTextField nomeAlunoTextField;
    private javax.swing.JTextField nomeProfessorTextField;
    private javax.swing.JPanel professorButtonPanel;
    private javax.swing.JPasswordField senhaAlunoPasswordField;
    private javax.swing.JPasswordField senhaProfessorPasswordField;
    private javax.swing.JTextField serieTextField;
    private javax.swing.JLabel verSenhaAlunoLabel;
    private javax.swing.JLabel verSenhaProfessorLabel;
    private javax.swing.JButton voltarAlunoButton;
    private javax.swing.JButton voltarProfessorButton;
    // End of variables declaration                   
}
