import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author louis
 */
public class TelaManterCadastro extends javax.swing.JFrame {
    static int idLogin;
    static String cadastro;
    public int idLoginAluno;
    /**
     * Creates new form TelaManterCadastro
     */
    public TelaManterCadastro(int idLogin, String cadastro) {
        super("Quiz ArtVantGarde");
        initComponents();
        this.idLogin = idLogin;
        this.cadastro = cadastro;
        DAO dao = new DAO();
        if(cadastro.equals("aluno")){
            try{
               alunosTable.setModel(new CadastroAlunoTableModel());
            }catch (Exception e){
               JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogoPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alunosTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        senhaTextField = new javax.swing.JTextField();
        serieTextField = new javax.swing.JTextField();
        codMatriculaTextField = new javax.swing.JTextField();
        nomeCompletoTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        adicionarCadastroButton = new javax.swing.JButton();
        alterarCadastroButton = new javax.swing.JButton();
        removerCadastroButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        voltarButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jogoPanel.setBackground(new java.awt.Color(222, 209, 193));
        jogoPanel.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jogoPanel.setPreferredSize(new java.awt.Dimension(1596, 848));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\louis\\OneDrive\\Documentos\\Faculdade\\Projeto_Integrador_Interdisciplinar\\Imagens\\ArtVantGarde_logo2.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Cadastros - Aluno");

        alunosTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alunosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Login", "ID Aluno", "Email", "Senha", "Nome Completo", "Série", "Código de Matrícula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alunosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alunosTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(alunosTable);

        jPanel1.setBackground(new java.awt.Color(234, 229, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel3.setText("Senha:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel4.setText("Nome Completo:");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel5.setText("Série:");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        jLabel7.setText("Código de Matrícula:");

        emailTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        senhaTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N

        serieTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N

        codMatriculaTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N

        nomeCompletoTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(senhaTextField)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serieTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(codMatriculaTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeCompletoTextField)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(serieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(senhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codMatriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(234, 229, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 92, 147), 3));

        adicionarCadastroButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        adicionarCadastroButton.setText("Adicionar Cadastro");
        adicionarCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCadastroButtonActionPerformed(evt);
            }
        });

        alterarCadastroButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        alterarCadastroButton.setText("Alterar Cadastro");
        alterarCadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarCadastroButtonActionPerformed(evt);
            }
        });

        removerCadastroButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        removerCadastroButton.setText("Remover Cadatro");

        voltarButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        voltarButton1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        voltarButton1.setText("Menu Principal");
        voltarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adicionarCadastroButton)
                .addGap(18, 18, 18)
                .addComponent(alterarCadastroButton)
                .addGap(18, 18, 18)
                .addComponent(removerCadastroButton)
                .addGap(18, 18, 18)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(voltarButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarCadastroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerCadastroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterarCadastroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jogoPanelLayout = new javax.swing.GroupLayout(jogoPanel);
        jogoPanel.setLayout(jogoPanelLayout);
        jogoPanelLayout.setHorizontalGroup(
            jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogoPanelLayout.createSequentialGroup()
                .addGroup(jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jogoPanelLayout.createSequentialGroup()
                        .addGap(648, 648, 648)
                        .addComponent(jLabel1))
                    .addGroup(jogoPanelLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addGroup(jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jogoPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jogoPanelLayout.setVerticalGroup(
            jogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1596, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void alunosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alunosTableMouseClicked
        int selectedRows = alunosTable.getSelectedRow();
        emailTextField.setText((String) alunosTable.getValueAt(selectedRows, 2));
        senhaTextField.setText((String) alunosTable.getValueAt(selectedRows, 3));
        nomeCompletoTextField.setText((String) alunosTable.getValueAt(selectedRows, 4));
        serieTextField.setText((String) alunosTable.getValueAt(selectedRows, 5));
        codMatriculaTextField.setText((String) alunosTable.getValueAt(selectedRows, 6));
        idLoginAluno = (Integer)alunosTable.getValueAt(selectedRows, 0);
        
    }//GEN-LAST:event_alunosTableMouseClicked

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        TelaSelecionarCadastro frame = new TelaSelecionarCadastro();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void voltarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton1ActionPerformed
        TelaMenuPrincipalAdmin frame = new TelaMenuPrincipalAdmin(idLogin);
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_voltarButton1ActionPerformed

    private void adicionarCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCadastroButtonActionPerformed
        String email = emailTextField.getText();
        String senha = senhaTextField.getText();
        String nomeCompleto = nomeCompletoTextField.getText();
        String serie = serieTextField.getText();
        String codMatricula = codMatriculaTextField.getText();
        
        Login login = new Login(email, senha);
        DAO dao = new DAO();
        try {
            dao.novoLogin(login);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Problemas Técnicos");
        }
        try {
            int idLoginAlunoNovo = dao.pegarId(login);
            UsuarioAluno aluno = new UsuarioAluno(nomeCompleto, serie, codMatricula, idLoginAlunoNovo);
            dao.cadastroAluno(aluno);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Problemas Técnicos");
        }
        try{
           alunosTable.setModel(new CadastroAlunoTableModel());
        }catch (Exception e){
           JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
        }
        
    }//GEN-LAST:event_adicionarCadastroButtonActionPerformed

    private void alterarCadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarCadastroButtonActionPerformed
        String email = emailTextField.getText();
        String senha = senhaTextField.getText();
        String nomeCompleto = nomeCompletoTextField.getText();
        String serie = serieTextField.getText();
        String codMatricula = codMatriculaTextField.getText();
        Login login = new Login(email, senha);
        UsuarioAluno aluno = new UsuarioAluno(nomeCompleto, serie, codMatricula, idLoginAluno);
        System.out.println(idLoginAluno);
        DAO dao = new DAO();
        try {
            dao.alterarCadastro(login, idLoginAluno);
            System.out.println("oi");
            try{
                dao.alterarAluno(aluno);
                System.out.println("oii");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Problemas Técnicos");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "É preciso selecionar um cadastro!");
        }
        
        try{
           alunosTable.setModel(new CadastroAlunoTableModel());
        }catch (Exception e){
           JOptionPane.showMessageDialog(null, "Problemas técnicos!!");
        }
        
        
    }//GEN-LAST:event_alterarCadastroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManterCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManterCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManterCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManterCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManterCadastro(idLogin, cadastro).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarCadastroButton;
    private javax.swing.JButton alterarCadastroButton;
    private javax.swing.JTable alunosTable;
    private javax.swing.JTextField codMatriculaTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jogoPanel;
    private javax.swing.JTextField nomeCompletoTextField;
    private javax.swing.JButton removerCadastroButton;
    private javax.swing.JTextField senhaTextField;
    private javax.swing.JTextField serieTextField;
    private javax.swing.JButton voltarButton;
    private javax.swing.JButton voltarButton1;
    // End of variables declaration//GEN-END:variables
}
