/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quizartvantgarde;

import javax.swing.JOptionPane;

/**
 *
 * @author louis
 */
public class TelaNovoCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaNovoCadastro
     */
    public TelaNovoCadastro() {
        super("Quiz ArtVantGarde");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        criarCadastroLabel = new javax.swing.JLabel();
        insiraEmailLabel = new javax.swing.JLabel();
        novoLoginTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        criarLoginButton = new javax.swing.JButton();
        voltarButton1 = new javax.swing.JButton();
        senhaConfirmaPasswordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        senhaPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 209, 193));
        jPanel1.setPreferredSize(new java.awt.Dimension(1596, 848));

        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\louis\\OneDrive\\Imagens\\ArtVantGarde_logo.png")); // NOI18N

        criarCadastroLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        criarCadastroLabel.setText("Criar Cadastro");

        insiraEmailLabel.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        insiraEmailLabel.setText("Insira seu email:");

        novoLoginTextField.setBackground(new java.awt.Color(238, 238, 238));
        novoLoginTextField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        novoLoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoLoginTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setText("Insira sua senha:");

        criarLoginButton.setBackground(new java.awt.Color(238, 238, 238));
        criarLoginButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        criarLoginButton.setText("Próximo");
        criarLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarLoginButtonActionPerformed(evt);
            }
        });

        voltarButton1.setBackground(new java.awt.Color(238, 238, 238));
        voltarButton1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        voltarButton1.setText("Voltar");
        voltarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButton1ActionPerformed(evt);
            }
        });

        senhaConfirmaPasswordField.setBackground(new java.awt.Color(238, 238, 238));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel2.setText("Confirme a senha:");

        senhaPasswordField.setBackground(new java.awt.Color(238, 238, 238));
        senhaPasswordField.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(619, 619, 619)
                        .addComponent(voltarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(criarLoginButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(654, 654, 654)
                        .addComponent(criarCadastroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(691, 691, 691)
                        .addComponent(insiraEmailLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(688, 688, 688)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(687, 687, 687)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(logoLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(539, 539, 539)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(senhaPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                            .addComponent(senhaConfirmaPasswordField)
                            .addComponent(novoLoginTextField))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criarCadastroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insiraEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaConfirmaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criarLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoLoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoLoginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoLoginTextFieldActionPerformed

    private void criarLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarLoginButtonActionPerformed
        String novoEmail = novoLoginTextField.getText();
        String novaSenha = new String(senhaPasswordField.getPassword());
        String confirmacaoSenha = new String(senhaConfirmaPasswordField.getPassword());

        if(novaSenha.equals(confirmacaoSenha)){
            try{
                System.out.println("try");
                Login login = new Login(novoEmail, novaSenha);
                // CriarLogin novoCadastro = new CriarLogin(novoEmail, novaSenha);
                DAO dao = new DAO();
                System.out.println("criando de classe");
                if(dao.existe(login)){
                    JOptionPane.showMessageDialog(null, "O usuário já existe! Insira outro email!");
                }else{
                    System.out.println("usuario nao existe");
                    // dao.novoLogin(novoCadastro);
                    // int idNovoCadastro = dao.pegarId(novoCadastro.getNovoLogin(), novoCadastro.getNovaSenha());
                    System.out.println("pegou o id");
                    if(novoEmail.endsWith("@jpiaget.pro.com.br")){
                        System.out.println("if professor");
                        TelaCadastroProfessor frame = new TelaCadastroProfessor(login);
                        System.out.println("abriu prof");
                        this.dispose();
                        frame.setVisible(true);
                        System.out.println("fechou");
                    }else if(novoEmail.contains("@")){
                        TelaCadastroAluno frame = new TelaCadastroAluno(login);
                        this.dispose();
                        frame.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "O método de login inserido é invalido, por favor certifique-se de que você inseriu um email.", "Quiz ArtVantGarde", 0);
                    }
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Problemas Técnicos!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "As senhas inseridas são diferentes, certifique-se de inserir a mesma senha.", "Quiz ArtVantGarde", 0);
        }
    }//GEN-LAST:event_criarLoginButtonActionPerformed

    private void voltarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButton1ActionPerformed
        TelaFazerLogin frame = new TelaFazerLogin();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_voltarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel criarCadastroLabel;
    private javax.swing.JButton criarLoginButton;
    private javax.swing.JLabel insiraEmailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField novoLoginTextField;
    private javax.swing.JPasswordField senhaConfirmaPasswordField;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JButton voltarButton1;
    // End of variables declaration//GEN-END:variables
}
